ignore:
  - "src/motorcad/core/rpc_methods_core_old.py"   # Just contains layer to run old scripts - deprecated
  
comment:
  layout: "diff"
  behavior: default
  
coverage:
  status:
    project:
      default:
        # basic
        # target: 50%
        threshold: 0%
        # advanced
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
    patch:
      default:
        # basic
        target: 80%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error

