comment:
  layout: "diff"
  behavior: default
  
coverage:
  status:
    project: false
    patch:
      default:
        # basic
        target: 80%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
  ignore:
    - "src/ansys/motorcad/core/rpc_methods_core_old.py"   # Just contains layer to run old scripts - deprecated
    - "src/ansys/motorcad/core/methods/rpc_methods_internal.py"   # Internal methods - users are warned that these are undocumented/untested/deprecated
