name: GitHub CI
on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.12'
  LIBRARY_NAME: ansys-motorcad-core
  LIBRARY_NAMESPACE: 'ansys.motorcad.core'
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  DOCUMENTATION_CNAME: 'motorcad.docs.pyansys.com'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    name: Tests and coverage
    runs-on: [self-hosted, pymotorcad, tests]
    steps:
      - name: Add Git Bash to Path
        run: |
          "$env:ProgramFiles\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python ${{ env.MAIN_PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions
          
      - name: Test with tox
        # Only the tox environment specified in the tox.ini gh-actions is run
        run: tox -e py312-coverage
        
      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        name: 'Upload coverage to Codecov'
